name: receptio
description: The mobile implementation of Receptio. Built using Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Value equality
  equatable: ^0.4.0
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+2
  bloc: ^4.0.0
  injectable: ^0.4.0
  get_it: ^4.0.1
  flutter_bloc: ^4.0.0
  flutter_typeahead: ^1.8.0
  flutter_auth0: ^0.5.0

dev_dependencies:
  build_runner: ^1.8.1
  injectable_generator: ^0.4.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:
  uses-material-design: true

  assets:
    - images/food-background.jpg
